CREATE TABLE item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN
);

CREATE TABLE book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    publisher TEXT,
    cover_state TEXT
);

CREATE TABLE music_album (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    on_spotify BOOLEAN
);

CREATE TABLE movie (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    silent BOOLEAN
);

CREATE TABLE game (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    multiplayer BOOLEAN,
    last_played_at DATE
);

CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
);

CREATE TABLE author (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100),
    last_name varchar(100),
);

CREATE TABLE source (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE label (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100),
    color varchar(100)
);

ALTER TABLE item ADD CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genre(id) ON DELETE CASCADE;
ALTER TABLE item ADD CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE;
ALTER TABLE item ADD CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES source(id) ON DELETE CASCADE;
ALTER TABLE item ADD CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES label(id) ON DELETE CASCADE;
