CREATE TABLE item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN
);

CREATE TABLE book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher TEXT,
    cover_state TEXT
) INHERITS (item);

CREATE TABLE music_album (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    on_spotify BOOLEAN
);

CREATE TABLE movie (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    silent BOOLEAN
);

CREATE TABLE game (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    multiplayer BOOLEAN,
    last_played_at DATE
);